# fly.toml app configuration file generated for cinema-api on 2023-05-17T10:05:52-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "cinema-api"
primary_region = "sea"

[env]
  ENVIRONMENT = "dev"
  YOUTUBE_API_KEY = "xxx"
  PORT = 8080
  TINI_SUBREAPER = 1

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [services.concurrency]
    hard_limit = 50
    soft_limit = 25

  [[services.http_checks]]
    interval = "60s"
    method = "get"
    path = "/"
    protocol = "http"
    timeout = "2s"
    tls_skip_verify = true

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    interval = "60s"
    timeout = "2s"